name: Group43Assignment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - '**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Ensure text file contains correct user ID
        id: process_files
        run: |
          branch_name="${GITHUB_REF##*/}"  # get branch name
          student_id="${branch_name%%-*} #save student ID
          echo "Student ID: $student_id"
          
          txt_files=$(ls *.txt 2>/dev/null) # check if .txt files in push

          if [ -z "$txt_files" ]; then
            echo "No text files found to process." 
            exit 0
          fi
          
          for file in $txt_files; do
            file_student_id="${file%%_*}"  # get file student id
            
            if [ "$file_student_id" != "$student_id" ]; then
              echo "Filename $file does not match branch student ID $student_id."
              # Create new file with correct ID
              new_file="${student_id}_${file#*_}"
              echo "Creating new file: $new_file"
              echo "Processed content of $file" > "$new_file"  # write content to new file
            else
              echo "Processing $file"
              echo "Processed content of $file" > "$file"  # Overwrite the original file
            fi
          done

          # Stage the modified files for commit
          git add *.txt
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Processed text files"
            git push origin "${{ github.ref }}"
          else
            echo "No changes to commit"
          fi
