name: Group43Assignment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - '**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Ensure text file contains correct user ID
        id: process_files
        run: |
          branch_name="${GITHUB_REF##*/}"  # get branch name
          student_id="${branch_name%%-*} #save student ID
          echo "User with student ID: $student_id is pushing changes"
          
          # Check for .txt files in push
          txt_files=$(ls *.txt 2>/dev/null)

          if [ -z "$txt_files" ]; then
            echo "No text files found to process." 
            exit 0
          fi

          # Output the names of the modified or added text files
          echo "The following text files are being modified or added:"
          for file in $txt_files; do
            echo "$file"
          done
